routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');
Route::resource('/consultas_web', 'ConsultasController');

Route::get('/contacto', function () { return view('publico.contacto'); });
Route::get('/consultas', function () { return view('publico.consultas'); });

Route::get('/', function () {
    return view('welcome');
    // return redirect('/login');
});

Route::get('reprocann/pacientes/formulario/get_url', 'PacientesController@getFormularioUrl')->name('formulario.url')->middleware('auth');
Route::get('reprocann/pacientes/formulario/{token}', 'PacientesController@formularioCreate')->name('formulario');
Route::post('reprocann/pacientes/formulario/{token}', 'PacientesController@formularioStore')->name('formulario.store');
Route::get('reprocann/pacientes/{id}/edit/formulario/{token}', 'PacientesController@formularioEdit')->name('formulario.edit');
Route::patch('reprocann/pacientes/{id}/edit/formulario/{token}', 'PacientesController@formularioUpdate')->name('formulario.update');

Route::group(['middleware' => 'auth'], function()
{
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/panel', 'PanelController@index')->name('panel');
	Route::get('/clientes/search', 'ClientesController@search');
	Route::get('/clientes/historial/{cliente_id}', 'ClientesController@historial');
	Route::post('/clientes/solicitudes/{cliente_id}', 'ClientesController@solicitudes');
	Route::resource('/clientes', 'ClientesController');
	Route::resource('/empresas', 'EmpresasController');
	Route::resource('/creditos', 'CreditosController');
	Route::resource('/usuarios', 'UsersController');
	Route::get('/get_pdf/{id}', 'CreditosController@pdf');
	Route::resource('/tareas', 'TareasController');
	
	Route::resource('reprocann/doctores', 'DoctoresController');
	Route::get('reprocann/doctores/{id}/documentos', 'DoctoresController@documentos')->name('doctores.documentos');
	Route::resource('reprocann/pacientes', 'PacientesController');
	Route::get('reprocann/pacientes/{id}/documentos', 'PacientesController@documentos')->name('pacientes.documentos');
  Route::get('reprocann/pacientes-export', 'PacientesController@export')->name('pacientes.export');
	Route::resource('reprocann/documentos', 'DocumentosController');
	Route::delete('reprocann/documentos/{id_paciente}/vencidos', 'DocumentosController@destroyVencidos')->name('documentos.destroy_vencidos');
	Route::get('reprocann/documentos/{id}/descargar_ci', 'DocumentosController@descargarCI')->name('documentos.descargar_ci');
	Route::get('reprocann/documentos/{id}/descargar_dj', 'DocumentosController@descargarDJ')->name('documentos.descargar_dj');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function scopeFiltros($query, $filtros)
    {
        // dd($filtros);

        foreach ($filtros as $name => $filtro) 
        {
            if ($filtro['text']) 
            {
            
                if(trim($filtro['text']) != "" &&  $filtro['tipo'] == 'text' )
                {
                    $string = $filtro['text'];
                    $query->where($name, 'LIKE' , "%$string%");
                }
                if(trim($filtro['text']) != "" &&  $filtro['tipo'] == 'number' )
                {
                    $query->where($name, '=' , $filtro['text']);
                }

            }
        }
    }


    public function roles()
    {
        return $this->belongsToMany(Role::class, 'role_users');
    }

    public function hasRole($role){

        if(is_string($role))
        {
            return $this->roles->contains('nombre', $role);
        }
        // return !!$role->intersect($this->roles)->count();
        return false;
    }

    public function tareas()
    {
        return $this->hasMany('App\Tarea');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

// use App\Http\Requests;
use Illuminate\Http\Request;
use App\User;
use Auth;


class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
       $this->authorize('admin', Auth::user());

        $filtros['name']      = array('text'=>$request->get('name'), 'tipo'=>'text');
        $filtros['email']       = array('text'=>$request->get('email'), 'tipo'=>'text');

        $data['users'] = User::filtros($filtros)->paginate(10);
        return view('users.index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nombre' => 'required|max:255',
            'telefonos' => 'required',
        ]);

        // $empresa = new User;
        // $empresa->nombre = $request->nombre;
        // $empresa->email = $request->email;
        // $empresa->save();

        $request->session()->flash('status', 'Empresa creada correctamente');
        $request->session()->flash('class', 'alert-success');

        return redirect(route('users.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('users.show')->with('user', $user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('users.edit')->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'email' => 'required',
        ]);

        $empresa = User::find($id);
        $empresa->name = $request->name;
        $empresa->email = $request->email;
        $empresa->update();

        $request->session()->flash('status', 'Usuario modificado correctamente');
        $request->session()->flash('class', 'alert-success');

        return redirect(route('usuarios.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $empresa = User::find($id);
        $empresa->delete();

        $request->session()->flash('status', 'Usuario Eliminado correctamente');
        $request->session()->flash('class', 'alert-success');

        return redirect(route('usuarios.index'));
    }
}

resources/views/users/edit.blade.php
@extends('layouts.app')
@section('header_title', 'Modificación de Usuario')
@section('header_subtitle', 'Modifica un usuario del sistema.')

@section('camino')
  <ol class="breadcrumb">
    <li><a href="{{url('/home')}}"><i class="fa fa-home"></i> Home</a></li>
    <li><a href="{{url('/usuarios')}}"><i class="fa fa-users"></i> Usuarios</a></li>
    <li class="active"> <i class="fa fa-pencil"></i> Modificación de usuario</li>
  </ol>
@endsection

@section('content')
    
    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="box box-primary">

            <div class="box-body">

        	 	{!! Form::model($user, ['route' => ['usuarios.update', $user->id], 'method' => 'patch']) !!}

                    @include('users.fields')

               	{!! Form::close() !!}

            </div>
        </div>
      </div>
    </div>
@endsection

resources/views/users/fields.blade.php
<!-- Nombre Field -->
<div class="form-group">
    {!! Form::label('name', 'Nombre:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>


<div class="form-group">
    {!! Form::label('email', 'E-mail:') !!}
      {!! Form::text('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('usuarios.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/users/index.blade.php
@extends('layouts.app')
@section('header_title', 'Usuarios')
@section('header_subtitle', 'Listado de usuarios del sistema.')

@section('camino')
  <ol class="breadcrumb">
    <li><a href="{{url('/home')}}"><i class="fa fa-home"></i> Home</a></li>
    <li class="active"> <i class="fa fa-users"></i> Usuarios</li>
  </ol>
@endsection

@section('content')

  <div class="row">
  	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  	 	<div class="box box-primary">
      	<div class="box-header with-border">
        	<h3 class="box-title">Listado de usuarios</h3>
	        <div class="box-tools pull-right">
	        	<a href="{{url('register')}}"  class="btn btn-primary btn-sm"  title=""><i class="fa fa-plus"></i> Agregar Usuario</a>
	          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
	          {{-- <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button> --}}
	        </div>
	      </div>
	      <div class="box-body">
          @if(session('status') != '')
            <div class="alert {{session('class')}}" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              {{session('status')}}
            </div>
          @endif
          
	        <div class="table-responsive">
	        	<table class="table table-hover">
	        		<thead>
	        			<tr>
	        				<th>NOMBRE</th>
	        				<th>EMAIL</th>
	        			</tr>
	        			<tr>
	        			{!!Form::model(Request::all(), ['url'=>'usuarios', 'method'=>'GET'])!!}
                  <td>{!! Form::text('name', null , ['class'=>'form-control', 'placeholder'=>'Buscar Nombre']) !!}</td>
                  <td>{!! Form::text('email', null , ['class'=>'form-control' , 'placeholder'=>'Buscar E-mail']) !!}</td>
                  <td>
                    <div class="btn-group">
                      <button type="submit" class="btn btn-default btn-sm"><i class="fa fa-search"></i> Buscar</button>
                      <a href="{{url('/usuarios')}}" class="btn  btn-sm btn-danger" title="Quitar filtros"><i class="fa fa-ban"></i> Quitar filtros</a>
                    </div>
                  </td>
                {!!Form::close()!!}
                </tr>
	        		</thead>
	        		<tbody>
	        			@foreach ($users as $e)
		        			<tr>
		        				<td>{{$e->name}}</td>
		        				<td>{{$e->email}}</td>
		        				<td style="width: 200px;">
                      <div class="pull-right" >
                        {!! Form::open(['route' => ['usuarios.destroy', $e->id], 'method' => 'delete']) !!}
                        <div class='btn-group'>
                          <a href="{{ route('usuarios.show', $e->id) }}" class='btn btn-default btn-xs'>
                             <i class="glyphicon glyphicon-eye-open"></i>
                          </a>

                          <a href="{{ route('usuarios.edit', $e->id) }}" class='btn btn-default btn-xs'>
                            <i class="fa fa-pencil"></i>
                          </a>
                          
                          {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
                            'type' => 'submit',
                            'class' => 'btn btn-danger btn-xs eliminar_swal',
                            'data-url_eliminar' => "url('usuarios.destroy')"
                          ]) !!}
                        </div>
                        {!! Form::close() !!}
                      </div>
                    </td>
		        			</tr>
	        			@endforeach
	        		</tbody>
	        	</table>
	        	{!! $users->appends($_GET)->links() !!}
	        </div>
	      </div>
    	</div>
  </div>

	</div>

@endsection

resources/views/users/show.blade.php
@extends('layouts.app')
@section('header_title', 'Detalle Usuario')
@section('header_subtitle', 'Muestra detalle de un usuario.')

@section('camino')
  <ol class="breadcrumb">
    <li><a href="{{url('/home')}}"><i class="fa fa-home"></i> Home</a></li>
    <li><a href="{{url('/usuarios')}}"><i class="fa fa-users"></i> Usuasrios</a></li>
    <li class="active"> <i class="fa fa-eye"></i> Ver usuarios</li>
  </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row" style="padding-left: 20px">
                        @include('users.show_fields')
                        <a href="{!! route('usuarios.index') !!}" class="btn btn-default"><i class="fa fa-undo"></i> Regresar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/show_fields.blade.php
<!-- Nombre Field -->
<div class="form-group">
    {!! Form::label('name', 'Nombre:') !!}
    <p>{!! $user->name !!}</p>
</div>

<!-- Rubro Id Field -->
<div class="form-group">
    {!! Form::label('email', 'Correo electrónico:') !!}
    <p>{!! $user->email !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Creado el:') !!}
    <p>{!! $user->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Modificado el:') !!}
    <p>{!! $user->updated_at !!}</p>
</div>