routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');
Route::resource('/consultas_web', 'ConsultasController');

Route::get('/contacto', function () { return view('publico.contacto'); });
Route::get('/consultas', function () { return view('publico.consultas'); });

Route::get('/', function () {
    return view('welcome');
    // return redirect('/login');
});

Route::get('reprocann/pacientes/formulario/get_url', 'PacientesController@getFormularioUrl')->name('formulario.url')->middleware('auth');
Route::get('reprocann/pacientes/formulario/{token}', 'PacientesController@formularioCreate')->name('formulario');
Route::post('reprocann/pacientes/formulario/{token}', 'PacientesController@formularioStore')->name('formulario.store');
Route::get('reprocann/pacientes/{id}/edit/formulario/{token}', 'PacientesController@formularioEdit')->name('formulario.edit');
Route::patch('reprocann/pacientes/{id}/edit/formulario/{token}', 'PacientesController@formularioUpdate')->name('formulario.update');

Route::group(['middleware' => 'auth'], function()
{
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/panel', 'PanelController@index')->name('panel');
	Route::get('/clientes/search', 'ClientesController@search');
	Route::get('/clientes/historial/{cliente_id}', 'ClientesController@historial');
	Route::post('/clientes/solicitudes/{cliente_id}', 'ClientesController@solicitudes');
	Route::resource('/clientes', 'ClientesController');
	Route::resource('/empresas', 'EmpresasController');
	Route::resource('/creditos', 'CreditosController');
	Route::resource('/usuarios', 'UsersController');
	Route::get('/get_pdf/{id}', 'CreditosController@pdf');
	Route::resource('/tareas', 'TareasController');
	
	Route::resource('reprocann/doctores', 'DoctoresController');
	Route::get('reprocann/doctores/{id}/documentos', 'DoctoresController@documentos')->name('doctores.documentos');
	Route::resource('reprocann/pacientes', 'PacientesController');
	Route::get('reprocann/pacientes/{id}/documentos', 'PacientesController@documentos')->name('pacientes.documentos');
  Route::get('reprocann/pacientes-export', 'PacientesController@export')->name('pacientes.export');
	Route::resource('reprocann/documentos', 'DocumentosController');
	Route::delete('reprocann/documentos/{id_paciente}/vencidos', 'DocumentosController@destroyVencidos')->name('documentos.destroy_vencidos');
	Route::get('reprocann/documentos/{id}/descargar_ci', 'DocumentosController@descargarCI')->name('documentos.descargar_ci');
	Route::get('reprocann/documentos/{id}/descargar_dj', 'DocumentosController@descargarDJ')->name('documentos.descargar_dj');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') , 'Unicred' }}</title>
    <link rel="shortcut icon" href="{{ asset('img/uc.ico') }}">

    <!-- Styles -->
    {{-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> --}}
    
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="{{ asset('admin_lte/bootstrap/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('admin_lte/dist/css/AdminLTE.min.css') }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
        folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('admin_lte/dist/css/skins/_all-skins.min.css') }}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/iCheck/flat/blue.css') }}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/morris/morris.css') }}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/jvectormap/jquery-jvectormap-1.2.2.css') }}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/datepicker/datepicker3.css') }}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/daterangepicker/daterangepicker.css') }}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">
    <!-- sweetalert2 -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/sweetalert2/sweetalert2.min.css') }}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/select2/select2.min.css') }}">

    @yield('styles')

    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body class="hold-transition skin-black sidebar-mini">
    <div class="wrapper">
         @include('layouts.top_navbar')
         @include('layouts.side_navbar')

        <div class="content-wrapper">

          <section class="content-header">
            <h1>
               @yield('header_title')
              <small>@yield('header_subtitle')</small>
            </h1>
            @yield('camino')
           
          </section>

          <section class="content">
            @yield('content')
          </section>

        </div>

        @include('layouts.footer')
               
    </div>

    <!-- Scripts -->
    
    <!-- jQuery 2.2.3 -->
    <script src="{{ asset('admin_lte/plugins/jQuery/jquery-2.2.3.min.js') }}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.6 -->
    <script src="{{ asset('admin_lte/bootstrap/js/bootstrap.min.js') }}"></script>
    <!-- Morris.js charts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="{{ asset('admin_lte/plugins/morris/morris.min.js') }}"></script>
    <!-- Sparkline -->
    <script src="{{ asset('admin_lte/plugins/sparkline/jquery.sparkline.min.js') }}"></script>
    <!-- jvectormap -->
    <script src="{{ asset('admin_lte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
    <script src="{{ asset('admin_lte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{{ asset('admin_lte/plugins/knob/jquery.knob.js') }}"></script>
    <!-- daterangepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
    <script src="{{ asset('admin_lte/plugins/daterangepicker/daterangepicker.js') }}"></script>
    <!-- datepicker -->
    <script src="{{ asset('admin_lte/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
    <script src="{{ asset('admin_lte/plugins/datepicker/locales/bootstrap-datepicker.es.js') }}"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="{{ asset('admin_lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
    <!-- Slimscroll -->
    <script src="{{ asset('admin_lte/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('admin_lte/plugins/fastclick/fastclick.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('admin_lte/dist/js/app.min.js') }}"></script>
    <!-- Sweetalert2 -->
    <script src="{{ asset('admin_lte/plugins/sweetalert2/sweetalert2.min.js') }}"></script>
    <!-- Select2 -->
    <script src="{{ asset('admin_lte/plugins/select2/select2.min.js') }}"></script>
    <script src="{{ asset('admin_lte/plugins/select2/i18n/es.js') }}"></script>
    <!-- custom js -->
    <script src="{{ asset('js/main.js') }}"></script>

    @yield('scripts')
</body>
</html>

resources/views/layouts/basic_layout.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') , 'Unicred' }}</title>

    <!-- Styles -->
    {{-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> --}}
    
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="{{ asset('admin_lte/bootstrap/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('admin_lte/dist/css/AdminLTE.min.css') }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
        folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('admin_lte/dist/css/skins/_all-skins.min.css') }}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/iCheck/flat/blue.css') }}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/morris/morris.css') }}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/jvectormap/jquery-jvectormap-1.2.2.css') }}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/datepicker/datepicker3.css') }}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/daterangepicker/daterangepicker.css') }}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">

    @yield('styles')

    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body class="hold-transition skin-purple sidebar-mini" 
        style="background-image: url('https://www.incimages.com/uploaded_files/image/970x450/getty_459097117_89221.jpg');
        background-repeat: no-repeat;
        background-size: cover;
        background-color: #555299;">

	

	@include('layouts.top_navbar')
	@yield('content')
    {{-- @include('layouts.footer') --}}
                
    

    <!-- Scripts -->
    <!-- jQuery 2.2.3 -->
    <script src="{{ asset('admin_lte/plugins/jQuery/jquery-2.2.3.min.js') }}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.6 -->
    <script src="{{ asset('admin_lte/bootstrap/js/bootstrap.min.js') }}"></script>
    <!-- Morris.js charts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="{{ asset('admin_lte/plugins/morris/morris.min.js') }}"></script>
    <!-- Sparkline -->
    <script src="{{ asset('admin_lte/plugins/sparkline/jquery.sparkline.min.js') }}"></script>
    <!-- jvectormap -->
    <script src="{{ asset('admin_lte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
    <script src="{{ asset('admin_lte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{{ asset('admin_lte/plugins/knob/jquery.knob.js') }}"></script>
    <!-- daterangepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
    <script src="{{ asset('admin_lte/plugins/daterangepicker/daterangepicker.js') }}"></script>
    <!-- datepicker -->
    <script src="{{ asset('admin_lte/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="{{ asset('admin_lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
    <!-- Slimscroll -->
    <script src="{{ asset('admin_lte/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('admin_lte/plugins/fastclick/fastclick.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('admin_lte/dist/js/app.min.js') }}"></script>

    @yield('scripts')
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="main-footer">
<div class="pull-right hidden-xs">
  <b>Version</b> 1.0.0
</div>
<strong>Copyright &copy; 2017 <a href="https://softwareadvanced.com">Software Advanced</a>.</strong>
todos los derechos reservados.
</footer>

resources/views/layouts/side_navbar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="{{ asset('admin_lte/dist/img/user.png') }}" class="img-circle" alt="User Image">
      </div>
      @if (!Auth::guest())
        <div class="pull-left info">
          <p>{{ Auth::user()->name }}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      @endif
    </div>
    <!-- search form -->
    <form action="{{url('/clientes/search')}}" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="search" class="form-control" placeholder="Search...">
            <span class="input-group-btn">
              <button type="submit" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
      </div>
    </form>
    <!-- /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MENÚ PRINCIPAL</li>
      <li class="{{ isActiveRoute('home') }}">
        <a href="{{ url('/home')}}">
          <i class="fa fa-home text-yellow"></i> 
          <span>Inicio</span>
          <span class="pull-right-container">
            {{-- <small class="label pull-right bg-blue">17</small> --}}
          </span>
        </a>
      </li>
       @can('admin', Auth::user())
        <li class="{{ isActiveRoute('panel') }}">
          <a href="{{url('panel')}}"><i class="fa fa-dashboard text-yellow"></i> 
            <span>Panel</span>
            <span class="pull-right-container">
              {{-- <small class="label pull-right bg-red">{{ App\User::count() }}</small> --}}
            </span>
          </a>
        </li>
      @endcan
      <li class="{{ isActiveRoute('clientes') }}">
        <a href="{{url('clientes')}}"><i class="fa fa-users text-yellow"></i> 
          <span>Clientes</span>
          <span class="pull-right-container">
            <small class="label pull-right bg-blue">{{ App\Cliente::count() }}</small>
          </span>
        </a>
      </li>
      <li class="{{ isActiveRoute('creditos') }}">
        <a href="{{url('creditos')}}"><i class="fa fa-money text-yellow"></i>
          <span>Créditos</span>
          <span class="pull-right-container">
            <small class="label pull-right bg-yellow">{{ App\Credito::count() }}</small>
          </span>
        </a>
      </li>
      <li class="{{ isActiveRoute('empresas') }}">
        <a href="{{url('empresas')}}"><i class="fa fa-building text-yellow"></i> 
          <span>Empresas</span>
          <span class="pull-right-container">
            <small class="label pull-right bg-aqua">{{ App\Empresa::count() }}</small>
          </span>
        </a>
      </li>
      @can('admin', Auth::user())
        <li class="{{ isActiveRoute('usuarios') }}">
          <a href="{{url('usuarios')}}"><i class="fa fa-user text-yellow"></i> 
            <span>Usuarios</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-red">{{ App\User::count() }}</small>
            </span>
          </a>
        </li>
         <li class="{{ isActiveRoute('tareas') }}">
          <a href="{{url('tareas')}}"><i class="fa fa-tasks text-yellow"></i> 
            <span>Tareas</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-red">{{ App\Tarea::count() }}</small>
            </span>
          </a>
        </li>
      @endcan

      <li class="{{ Request::is('reprocann*') ? 'active' : '' }}">
        <a href="#">
          <i class="fa fa-leaf text-green"></i> <span>Reprocann</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li class="{{ Request::is('reprocann/doctores*') ? 'active' : '' }}">
            <a href="{{route('doctores.index')}}">
              <i class="fa fa-user-md text-green"></i>
              <span> Doctores</span>
              <span class="pull-right-container">
                <small class="label pull-right bg-aqua">{{ App\Doctor::count() }}</small>
              </span>
            </a>
          </li>
          <li class="{{ Request::is('reprocann/pacientes*') ? 'active' : '' }}">
            <a href="{{route('pacientes.index')}}">
              <i class="fa fa-user text-green"></i>
              <span> Pacientes</span>
              <span class="pull-right-container">
                <small class="label pull-right bg-blue">{{ App\Paciente::count() }}</small>
              </span>
            </a>
          </li>
          <li class="{{ Request::is('reprocann/documentos*') ? 'active' : '' }}">
            <a href="{{route('documentos.index')}}">
              <i class="fa fa-file-text text-green"></i>
              <span> Documentos</span>
              <span class="pull-right-container">
                <small class="label pull-right bg-yellow">{{ App\Documento::count() }}</small>
              </span>
            </a>
          </li>
        </ul>
      </li>
      
      {{-- <li class="treeview">
        <a href="#">
          <i class="fa fa-share"></i> <span>Multilevel</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
          <li>
            <a href="#"><i class="fa fa-circle-o"></i> Level One
              <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
            </a>
            <ul class="treeview-menu">
              <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
              <li>
                <a href="#"><i class="fa fa-circle-o"></i> Level Two
                  <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                  </span>
                </a>
                <ul class="treeview-menu">
                  <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                  <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                </ul>
              </li>
            </ul>
          </li>
          <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
        </ul>
      </li> --}}

    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

resources/views/layouts/welcome_layout.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Préstamos personales"/>
    <meta name="robots" content="index,follow" />
    <meta name="keywords" content="unicred, prestamos, creditos, La Plata, efectivo"/>
    <link rel="canonical" href="http://unicred-prestamos.com/public" />


    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="shortcut icon" href="{{ asset('img/uc.ico') }}">

    <title>{{ config('app.name') , 'Fundación cannavis' }}</title>

    <!-- Styles -->
    {{-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> --}}
    
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="{{ asset('admin_lte/bootstrap/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('admin_lte/dist/css/AdminLTE.min.css') }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
        folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('admin_lte/dist/css/skins/_all-skins.min.css') }}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/iCheck/flat/blue.css') }}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/morris/morris.css') }}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/jvectormap/jquery-jvectormap-1.2.2.css') }}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/datepicker/datepicker3.css') }}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/daterangepicker/daterangepicker.css') }}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{ asset('admin_lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">

    <link rel="stylesheet" href="{{ asset('css/welcome.css') }}">

    

    @yield('styles')

    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body>

	@include('layouts.welcome_navbar')
	@yield('content')
    @include('publico.footer')

                
    

    <!-- Scripts -->
    {{-- <script src="{{ asset('js/app.js') }}"></script> --}}
    <!-- jQuery 2.2.3 -->
    <script src="{{ asset('admin_lte/plugins/jQuery/jquery-2.2.3.min.js') }}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.6 -->
    <script src="{{ asset('admin_lte/bootstrap/js/bootstrap.min.js') }}"></script>
    <!-- Morris.js charts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="{{ asset('admin_lte/plugins/morris/morris.min.js') }}"></script>
    <!-- Sparkline -->
    <script src="{{ asset('admin_lte/plugins/sparkline/jquery.sparkline.min.js') }}"></script>
    <!-- jvectormap -->
    <script src="{{ asset('admin_lte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
    <script src="{{ asset('admin_lte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{{ asset('admin_lte/plugins/knob/jquery.knob.js') }}"></script>
    <!-- daterangepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
    <script src="{{ asset('admin_lte/plugins/daterangepicker/daterangepicker.js') }}"></script>
    <!-- datepicker -->
    <script src="{{ asset('admin_lte/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="{{ asset('admin_lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
    <!-- Slimscroll -->
    <script src="{{ asset('admin_lte/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('admin_lte/plugins/fastclick/fastclick.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('admin_lte/dist/js/app.min.js') }}"></script>

    @yield('scripts')
</body>
</html>